---
language: ruby
rvm:
  - 1.9.3-p551
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-1.7.26
  - jruby-9.1.7.0
jdk:
  - oraclejdk8
script: |
  set -e
  bundle exec rake test
  mkdir -p pkg
  gem build *.gemspec
  gem spec *.gem version | grep -o 'version: .\+' | cut -d' ' -f2 | tee gem_version.txt
